### ISSUE TITLE
Quest status

### ISSUE THREAD

**Issue by disruption01** [widxwer/Questie#13]
Quest status doesn't update after quest is complete, sometimes I have to reload in order to fix it.

**Comment by widxwer** [comment]
Is it a specific quest, or are all quests affected? Could you at least provide a quest name or ID?

**Comment by disruption01** [comment]
all quests

**Comment by widxwer** [comment]
What do you mean by "quest status"? Do quest icons stay on the map/minimap after completion? I just checked, and everything works fine for me, at least in the starting area. Do you have the latest version installed?

**Comment by disruption01** [comment]
I have the latest version installed, I complete a quest and the world map icons stay the same like if was incomplete, the tracker aswell, I will try to provide pics in order to explain better

**Comment by disruption01** [comment]
here, I just delivered the daily dungeon quest

![image](https://github.com/widxwer/Questie/assets/44980177/7fa77b31-c634-42d7-862e-8e0ae02110d9)

the quest status stays the same

**Comment by widxwer** [comment]
There might be something wrong with that quest. It's not even listed on Wowhead as being ended by [Archmage Lan'dalock](https://www.wowhead.com/wotlk/npc=20735/archmage-landalock#ends).

**Comment by disruption01** [comment]
> There might be something wrong with that quest. It's not even listed on Wowhead as being ended by [Archmage Lan'dalock](https://www.wowhead.com/wotlk/npc=20735/archmage-landalock#ends).

This is a 3.3.5a client, and this server (whitemane) is running at Phase 1 which means that Archmage Lan'dalock will deliver a daily dungeon quest everyday

on wotlk wowhead and on wotlk classic the daily dungeon quest was mainly random (it was reworked)
https://www.wowhead.com/wotlk/quest=78753/proof-of-demise-threats-to-azeroth
but if you go deep you can find it by using the id itself
https://www.wowhead.com/wotlk/quest=13249/proof-of-demise-the-prophet-tharonja

before it was like this: (evowow is a 3.3.5a wowhead)
https://wotlk.evowow.com/?quest=13249

other quests following the same style
https://wotlk.evowow.com/?search=Proof+of+demise

**Even though I am discussing this specific quest, happens with every quest, I just gave an example.**

**Comment by widxwer** [comment]
The issue is that quests which are blacklisted by Questie (Questie-335\Database\Corrections\QuestieQuestBlacklist.lua) and apparently shouldn't be obtainable in Classic WoW can be picked up on private servers.

**Comment by disruption01** [comment]
ok but this is a 3.3.5a client branch right (only played in private servers)? most servers play progression style instead of full ICC/RS phase, I don't mind removing the "blacklist" part by myself.
stock Trinitycore is set on ICC/RS phase so it's never a good example.

**Comment by disruption01** [comment]
by that logic these shouldnt show up here then

![image](https://github.com/widxwer/Questie/assets/44980177/11b300a2-e865-4328-8657-3df6c0ffebef)

these are WOTLK classic quests

**Comment by disruption01** [comment]
https://wowwiki-archive.fandom.com/wiki/Proof_of_Demise#:~:text=Proof%20of%20Demise%20was%20an,complete%2C%20one%20for%20each%20quest.

![image](https://github.com/widxwer/Questie/assets/44980177/f6064168-2332-4a87-893c-7387142ba19d)


they were removed with the introduction of ICC patch (but like I said, not all servers play ICC patch, mostly don't these days)

**Comment by disruption01** [comment]
https://github.com/Questie/Questie/commit/ce4851b03828efa71295de21ec663aa53149958d

this was when ICC patch went live on WOTLK classic, thats why it was hidden

anyway, maybe we can consider a feature of "phasing" on this 3.3.5a version? I can try to help implement it.

**Comment by disruption01** [comment]
![image](https://github.com/widxwer/Questie/assets/44980177/16100342-a55b-4fba-aaeb-2d18d3c7a70c)

**Comment by disruption01** [comment]
@widxwer sorry for the spam, but this last comment I did illustrates the real problem

**Comment by widxwer** [comment]
@disruption01 Quest completion should work now, even if the quest is blacklisted.

**Comment by Kahuma1** [comment]
Just tested it with Frenzyheart Tribe dailys
![grafik](https://github.com/widxwer/Questie/assets/92261432/59db94da-8504-4269-a832-0143090669ee)
Quest ist completed but objective is still shown on map.

**Comment by widxwer** [comment]
@Kahuma1 Can you check if it's fixed with the latest commit?

**Comment by Kahuma1** [comment]
Already did that Quest today, will tell you tomorrow.

**Comment by Kahuma1** [comment]
@widxwer seems to  be fixed

**Comment by disruption01** [comment]
not fixed for these quests

![image](https://github.com/widxwer/Questie/assets/44980177/012712c0-d394-4fa8-af8c-e967feacae03)

after you complete once, the second time you go for them it wont show on map.

(these are repeatable from the wintersaber trainers - alliance)

**Comment by widxwer** [comment]
@disruption01 What exactly is not showing—the available/completed icon or the objectives markers? Can you also check the 'Doable' status in Journey?

**Comment by disruption01** [comment]
> @disruption01 What exactly is not showing—the available/completed icon or the objectives markers? Can you also check the 'Doable' status in Journey?

The markers wont show the second time doing the quests

**Comment by disruption01** [comment]
![image](https://github.com/widxwer/Questie/assets/44980177/05ab493c-71d2-4e28-8ed5-9ab8173a23be)

![image](https://github.com/widxwer/Questie/assets/44980177/9dfb9e02-20c4-4058-9817-14185c54f6e3)

![image](https://github.com/widxwer/Questie/assets/44980177/e35d2c07-e999-4256-8365-da12514af0cd)


I don't know if this helps. this happens after turning in the 2 repeatable quests.

**Comment by widxwer** [comment]
@disruption01 I have found what is causing this issue, but I don't have time to fix it right now.

**Comment by widxwer** [comment]
@disruption01 The issue with repeatable quests not displaying objectives on the map should be fixed in [commit 73c82e9](https://github.com/widxwer/Questie/commit/73c82e96ab679dba45072f936ebf9bbd81613d34).

**Comment by disruption01** [comment]
@widxwer thanks a lot for your work. it's fixed.
